---
name: Build and Push Container Image
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md' # Don't trigger builds for documentation changes
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read
  packages: write

env:
  major_version: "3"
  minor_version: "0.0"

jobs:
  build:
    name: Build and Push Container Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        id: launch_builder

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push API Image
        working-directory: ./api
        run: |
          docker buildx build --push --pull\
            --platform linux/amd64,linux/arm64\
            --build-arg VERSION=${{ env.major_version }}.${{ env.minor_version }}\
            --label "org.label-schema.vcs-ref=${{ github.sha }}"\
            --label "org.label-schema.version=${{ env.major_version }}.${{ env.minor_version }}"\
            --tag ghcr.io/jmanero/mempool/api:latest\
            --tag ghcr.io/jmanero/mempool/api:${{ env.major_version }}\
            --tag ghcr.io/jmanero/mempool/api:${{ env.major_version }}.${{ env.minor_version }}\
            --tag ghcr.io/jmanero/mempool/api:${{ env.major_version }}.${{ env.minor_version }}-${{ github.sha }}\
            --file Containerfile .

      - name: Build and Push Web Image
        working-directory: ./web
        run: |
          docker buildx build --push --pull\
            --platform linux/amd64,linux/arm64\
            --build-arg VERSION=${{ env.major_version }}.${{ env.minor_version }}\
            --label "org.label-schema.vcs-ref=${{ github.sha }}"\
            --label "org.label-schema.version=${{ env.major_version }}.${{ env.minor_version }}"\
            --tag ghcr.io/jmanero/mempool/web:latest\
            --tag ghcr.io/jmanero/mempool/web:${{ env.major_version }}\
            --tag ghcr.io/jmanero/mempool/web:${{ env.major_version }}.${{ env.minor_version }}\
            --tag ghcr.io/jmanero/mempool/web:${{ env.major_version }}.${{ env.minor_version }}-${{ github.sha }}\
            --file Containerfile .
